services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on: # <-- Reverted to simpler depends_on
      - postgres
      - redis
      - qdrant

  worker:
    build: .
    volumes:
      - ./app:/code/app
    env_file:
      - .env
    command: ["celery", "-A", "app.celery_worker.celery_app", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - postgres
      - qdrant

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  qdrant: # <-- The healthcheck block has been completely removed
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data: